name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: nvidia/cuda:11.6.0-base-ubuntu20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: make
